GET http://49.235.1.205:3000/person

###
GET http://49.235.1.205:3000/alarm/alarmId/0

###
GET http://localhost:3000/alarm/alarmlog


###

PATCH http://49.235.1.205:3000/person/5f972d88122b1d3eb625e166
Content-Type: application/json

{
}


###

GET http://localhost:3000/alarm/id/5f8968c052e7fb352c603af8


###

POST http://localhost:3000/alarm/create
Content-Type: application/json

{
    "Alarmlevel": 0,
    "AlarmDefinition": "test definition",
    "AlarmTrigger":"M3",
    "AlarmMax":2,
    "AlarmMin":0,
    "AlarmMessage": "This is a test alarm B!",
    "NormalizationMessage":"Normal text test",
    "NormalizationTime": "9:15 10-13-2020",
    "TriggerMode": 1
}

###
PATCH http://localhost:3000/alarm/update/6
Content-Type: application/json

{
    "TriggerValue":3,
    "TriggerStatus":0

}
// ""
###

PATCH http://localhost:3000/person/5f8c730c7dc85e2a10bd4ca5
Content-Type: application/json

{
    "admin": true
}


###

DELETE http://localhost:3000/person/5f8c729b441212457072ac42


###

GET http://localhost:3000/alarm//alarmId/4

###

DELETE  http://localhost:3000/alarm//alarmId/3






###

//login test part:
//get all data
GET http://localhost:3000/user

###

//login test part:
GET http://localhost:3000/user/id/5f8c3e928e00d10e9021863f

###
//delete
DELETE http://localhost:3000/user/5f8c3e928e00d10e9021863f

###

POST http://localhost:3000/user/regist
Content-Type: application/json

{
    "password": "test",
    "email": "aefasef",
    "personID": "afwefasfdsfefsaf"
}


###
//login
POST http://localhost:3000/user/login
Content-Type: application/json

{
    "password": "12345678910",
    "username": "test2"
}


###
POST http://localhost:3000/user/google
Content-Type: application/json

{
    "username":"test2",
    "email":"req.body.email",
    "uid":"sefasegdafgsefasef"
}




###
GET  http://192.168.10.116/cgi-bin/read_sps.cgi?init